#!/usr/bin/env bash
#
# This script depends on pandoc
#

die () {
	printf 'fatal: %b\n' "$@" >&2
	exit 1
}

build_src_pages () {
	template="$(<"src/template.html")"
	for md in src/*.md; do
		filename=${md##*/}
		html="${filename/%.md/.html}"
		[[ $html -ot $md ]] || continue
		printf '%s\n' "    GEN         ${html}"
		printf '%b' "${template/'{{content}}'/$(pandoc --from=markdown+footnotes "$md")}" >"${html}"
	done
}

build_man_pages () {
	if ! [[ -d ../labwc/build/docs ]]; then
		printf 'warn: %b\n' "Need labwc next to labwc.github.io with man pages built" >&2
		return
	fi
	template="$(sed -e 's/sans-serif/monospace/' src/template.html)"
	for scd in ../labwc/build/docs/*; do
		filename=${scd##*/}
		html=$(basename ${scd}).html
		[[ $html -ot $scd ]] || continue
		printf '%s\n' "    GEN         ${html}"
		printf '%b' "${template/'{{content}}'/$(pandoc --from man "$scd")}" >"${html}"
		./fix-bullet-formatting.py "${html}"
	done
}

main () {
	build_src_pages
	build_man_pages
}

main "$@"

